CREATE TABLE IF NOT EXISTS "GarbageCollection" (
	"StartTime"	DATETIME NOT NULL,
	"TCID"	INTEGER NOT NULL,
	"GCID"	INTEGER NOT NULL,
	"EndTime"	DATETIME NOT NULL,
	FOREIGN KEY("TCID") REFERENCES "TrashCan"("TCID") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "start_endGC" CHECK(EndTime>=StartTime),
	CONSTRAINT "gc_pk" PRIMARY KEY("StartTime","TCID","GCID"),
	FOREIGN KEY("GCID") REFERENCES "GarbageCollectionCompany"("GCID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "GarbageCollectionCompany" (
	"GCID"	INTEGER,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("GCID")
);
CREATE TABLE IF NOT EXISTS "TrashCan" (
	"TCID"	INTEGER,
	"NID"	INTEGER,
	PRIMARY KEY("TCID"),
	FOREIGN KEY("NID") REFERENCES "Neighborhood"("NID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "CarParking" (
	"CID"	INTEGER NOT NULL,
	"StartTime"	DATETIME NOT NULL,
	"EndTime"	DATETIME NOT NULL,
	"Cost"	FLOAT NOT NULL CHECK(Cost>=0),
	"AID"	INTEGER NOT NULL,
	FOREIGN KEY("CID") REFERENCES "Cars"("CID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("AID") REFERENCES "ParkingArea"("AID") ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT "cp_pk" PRIMARY KEY("CID","StartTime"),
	CONSTRAINT "start_endCP" CHECK(EndTime>=StartTime)
);
CREATE TABLE IF NOT EXISTS "Cars" (
	"CID"	INTEGER,
	"CellPhoneNumber"	VARCHAR(10) NOT NULL,
	"CreditCard"	VARCHAR(16),
	"ExpirationDate"	DATETIME,
	"ThreeDigits"	VARCHAR(3),
	"ID"	VARCHAR(9) NOT NULL,
	PRIMARY KEY("CID")
);
CREATE TABLE IF NOT EXISTS "ParkingArea" (
	"AID"	INTEGER,
	"Name"	VARCHAR(30) NOT NULL,
	"PricePerHour"	FLOAT NOT NULL CHECK(PricePerHour>=0),
	"MaxPricePerDay"	FLOAT NOT NULL CHECK(MaxPricePerDay>=0),
	"NID"	INTEGER NOT NULL,
	PRIMARY KEY("AID"),
	FOREIGN KEY("NID") REFERENCES "Neighborhood"("NID") ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT "maxPrice" CHECK(MaxPricePerDay>=PricePerHour)
);
CREATE TABLE IF NOT EXISTS "Resident" (
	"RID"	INTEGER,
	"FirstName"	VARCHAR(50) NOT NULL,
	"LastName"	VARCHAR(50) NOT NULL,
	"BirthDate"	DATETIME NOT NULL,
	"StreetName"	VARCHAR(50) NOT NULL,
	"Number"	INTEGER NOT NULL CHECK(Number>0),
	"Door"	INTEGER NOT NULL CHECK(Door>0),
	PRIMARY KEY("RID"),
	FOREIGN KEY("StreetName","Number","Door") REFERENCES "Apartment"("StreetName","Number","Door") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Apartment" (
	"StreetName"	VARCHAR(50) NOT NULL,
	"Number"	INTEGER NOT NULL CHECK(Number>0),
	"Door"	INTEGER NOT NULL CHECK(Door>0),
	"Type"	VARCHAR(20) NOT NULL,
	"SizeSquareMeter"	FLOAT CHECK(SizeSquareMeter>0),
	"NID"	INTEGER NOT NULL,
	FOREIGN KEY("NID") REFERENCES "Neighborhood"("NID") ON UPDATE RESTRICT ON DELETE CASCADE,
	CONSTRAINT "ap_pk" PRIMARY KEY("StreetName","Number","Door")
);
CREATE TABLE IF NOT EXISTS "Neighborhood" (
	"NID"	INTEGER,
	"Name"	VARCHAR(30) NOT NULL,
	PRIMARY KEY("NID")
);
CREATE TABLE IF NOT EXISTS "Project" (
	"PID"	INTEGER,
	"Name"	VARCHAR(50) NOT NULL,
	"Description"	TEXT,
	"Budget"	FLOAT NOT NULL CHECK(Budget>=0),
	"NID"	INTEGER NOT NULL,
	PRIMARY KEY("PID"),
	FOREIGN KEY("NID") REFERENCES "Neighborhood"("NID") ON UPDATE RESTRICT ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "ProjectConstructorEmployee" (
	"EID"	INTEGER NOT NULL,
	"PID"	INTEGER NOT NULL,
	"StartWorkingDate"	DATETIME,
	"EndWorkingDate"	DATETIME,
	"JobDescription"	TEXT,
	FOREIGN KEY("EID") REFERENCES "ConstructorEmployee"("EID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PID") REFERENCES "Project"("PID"),
	CONSTRAINT "pce_pk" PRIMARY KEY("EID","PID"),
	CONSTRAINT "ch_date" CHECK(StartWorkingDate<EndWorkingDate)
);
CREATE TABLE IF NOT EXISTS "Department" (
	"DID"	INTEGER,
	"Name"	VARCHAR(50) NOT NULL,
	"Description"	TEXT,
	"ManagerID"	INTEGER,
	PRIMARY KEY("DID"),
	FOREIGN KEY("ManagerID") REFERENCES "OfficialEmployee"("EID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "ConstructorEmployee" (
	"EID"	INTEGER,
	"CompanyName"	TEXT NOT NULL,
	"SalaryPerDay"	FLOAT NOT NULL CHECK(SalaryPerDay>0),
	PRIMARY KEY("EID"),
	FOREIGN KEY("EID") REFERENCES "Employee"("EID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "OfficialEmployee" (
	"EID"	INTEGER,
	"StartWorkingDate"	DATETIME NOT NULL,
	"Degree"	INTEGER NOT NULL CHECK(Degree>=0),
	"Department"	INTEGER NOT NULL,
	PRIMARY KEY("EID"),
	FOREIGN KEY("EID") REFERENCES "Employee"("EID") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("Department") REFERENCES "Department"("DID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "CellPhone" (
	"EID"	INTEGER NOT NULL,
	"Number"	VARCHAR(10) NOT NULL,
	CONSTRAINT "cl_pk" PRIMARY KEY("EID","Number"),
	FOREIGN KEY("EID") REFERENCES "Employee"("EID") ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Employee" (
	"EID"	INTEGER,
	"FirstName"	VARCHAR(50) NOT NULL,
	"LastName"	VARCHAR(50) NOT NULL,
	"BirthDate"	DATETIME NOT NULL,
	"City"	VARCHAR(35) NOT NULL,
	"StreetName"	VARCHAR(50) NOT NULL,
	"Number"	INTEGER NOT NULL CHECK(Number>0),
	"Door"	INTEGER CHECK(Door>0),
	PRIMARY KEY("EID")
);

